app.cdc-debezium.management.endpoints.web.exposure.include=health,info,bindings
app.cdc-debezium.management.metrics.tags.application.guid=${spring.cloud.application.guid:unknown}
app.cdc-debezium.management.metrics.tags.application.name=${vcap.application.application_name:${spring.cloud.dataflow.stream.app.label:unknown}}
app.cdc-debezium.management.metrics.tags.application.type=${spring.cloud.dataflow.stream.app.type:unknown}
app.cdc-debezium.management.metrics.tags.application=${spring.cloud.dataflow.stream.name:unknown}-${spring.cloud.dataflow.stream.app.label:unknown}-${spring.cloud.dataflow.stream.app.type:unknown}
app.cdc-debezium.management.metrics.tags.instance.index=${vcap.application.instance_index:${spring.cloud.stream.instanceIndex:0}}
app.cdc-debezium.management.metrics.tags.stream.name=${spring.cloud.dataflow.stream.name:unknown}
app.cdc-debezium.spring.cloud.stream.kafka.binder.brokers=PLAINTEXT://kafka-broker:9092
app.cdc-debezium.spring.cloud.stream.kafka.binder.zknodes=zookeeper:2181
app.cdc-debezium.spring.cloud.stream.kafka.streams.binder.brokers=PLAINTEXT://kafka-broker:9092
app.cdc-debezium.spring.cloud.stream.kafka.streams.binder.zknodes=zookeeper:2181
app.cdc-debezium.spring.kafka.streams.properties.metrics.recording.level=DEBUG
app.cdc-debezium.wavefront.application.name=${spring.cloud.dataflow.stream.name:unknown}
app.cdc-debezium.wavefront.application.service=${spring.cloud.dataflow.stream.app.label:unknown}-${spring.cloud.dataflow.stream.app.type:unknown}-${vcap.application.instance_index:${spring.cloud.stream.instanceIndex:0}}
app.jdbc.management.endpoints.web.exposure.include=health,info,bindings
app.jdbc.management.metrics.tags.application.guid=${spring.cloud.application.guid:unknown}
app.jdbc.management.metrics.tags.application.name=${vcap.application.application_name:${spring.cloud.dataflow.stream.app.label:unknown}}
app.jdbc.management.metrics.tags.application.type=${spring.cloud.dataflow.stream.app.type:unknown}
app.jdbc.management.metrics.tags.application=${spring.cloud.dataflow.stream.name:unknown}-${spring.cloud.dataflow.stream.app.label:unknown}-${spring.cloud.dataflow.stream.app.type:unknown}
app.jdbc.management.metrics.tags.instance.index=${vcap.application.instance_index:${spring.cloud.stream.instanceIndex:0}}
app.jdbc.management.metrics.tags.stream.name=${spring.cloud.dataflow.stream.name:unknown}
app.jdbc.spring.cloud.stream.kafka.binder.brokers=PLAINTEXT://kafka-broker:9092
app.jdbc.spring.cloud.stream.kafka.binder.zknodes=zookeeper:2181
app.jdbc.spring.cloud.stream.kafka.streams.binder.brokers=PLAINTEXT://kafka-broker:9092
app.jdbc.spring.cloud.stream.kafka.streams.binder.zknodes=zookeeper:2181
app.jdbc.spring.kafka.streams.properties.metrics.recording.level=DEBUG
app.jdbc.wavefront.application.name=${spring.cloud.dataflow.stream.name:unknown}
app.jdbc.wavefront.application.service=${spring.cloud.dataflow.stream.app.label:unknown}-${spring.cloud.dataflow.stream.app.type:unknown}-${vcap.application.instance_index:${spring.cloud.stream.instanceIndex:0}}
deployer.cdc-debezium.bootVersion=2
deployer.jdbc.bootVersion=2

# cdc-debezium source
app.cdc-debezium.cdc.connector=postgres
app.cdc-debezium.cdc.name=my-cdc
app.cdc-debezium.cdc.config.database.hostname=postgres
app.cdc-debezium.cdc.config.database.port=5432
app.cdc-debezium.cdc.config.database.user=root
app.cdc-debezium.cdc.config.database.password=rootpw
app.cdc-debezium.cdc.config.database.dbname=dataflow
app.cdc-debezium.cdc.config.database.server.name=my-server
app.cdc-debezium.cdc.config.table.include.list=public.source_table
app.cdc-debezium.cdc.config.plugin.name=pgoutput
# message format flattening
app.cdc-debezium.cdc.flattening.enabled=true

# jdbc sink
app.jdbc.spring.datasource.url=jdbc:postgresql://postgres:5432/dataflow
app.jdbc.spring.datasource.username=root
app.jdbc.spring.datasource.password=rootpw
app.jdbc.spring.datasource.driver-class-name=org.postgresql.Driver
app.jdbc.jdbc.consumer.table-name=target_table
app.jdbc.jdbc.consumer.columns=id,name,email